name: CI
on: push

jobs:
  deploy:
    name: Docker container with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Run container
        run: docker-compose up -d
      
      - name: Ngrok Tunnel Action
        uses: LuisBoto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 8000
          # ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          ngrok_authtoken: 2WLQGNHgnHIWYm5K2tuafAcJeZR_5BZcSjFbqu1sHmNNkW3yB
          tunnel_type: http
          save_url_to_filename: tunnelURL.md
